name: Deploy to waybross.com

# Run manually or on push to the main branch
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to waybross.com
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the latest code from GitHub
      - name: Get latest code
        uses: actions/checkout@v4

      # Step 2: Upload code via FTP
      - name: Deploy to InfinityFree via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: ${{ secrets.if0_40317158 }}
          password: ${{ secrets.M7cc9qGv4ow1p }}
          server-dir: /waybross.com/htdocs/  # For addon domains
          timeout: 86400000
          log-level: standard
